don't propagate dll's sanitizer configuration to the top level binary
Summary:
This fixes the following linker errors caused by D7304338 and D7222284 in sigma:
```lang=bash
third-party-buck/gcc-5-glibc-2.23/tools/binutils/bin/gold/ld: error: /data/users/sugak/s3/fbcode/buck-out/dev/gen/common/hs/util/reader-cxx-sanitizer-configuration-lib#gcc-5-glibc-2.23,static-pic/libreader-cxx-sanitizer-configuration-lib.a(/data/users/sugak/s3/fbcode/buck-out/dev/gen/common/hs/util/reader-cxx-sanitizer-configuration-lib#gcc-5-glibc-2.23,static-p
ic/../reader-cxx-sanitizer-configuration-lib#compile-pic-reader-cxx-sanitizer-configuration.c.o89245b11,gcc-5-glibc-2.23/reader-cxx-sanitizer-configuration.c.o): multiple definition of 'kUbsanDefaultOptions'
third-party-buck/gcc-5-glibc-2.23/tools/binutils/bin/gold/ld: /data/users/sugak/s3/fbcode/buck-out/dev/gen/tally/client/hs/types-cxx-sanitizer-configuration-lib#gcc-5-glibc-2.23,static-pic/libtypes-cxx-sanitizer-configuration-lib.a(/data/users/sugak/s3/fbcode/buck-out/dev/gen/tally/client/hs/types-cxx-sanitizer-configuration-lib#gcc-5-glibc-2.23,static-pic/../ty
pes-cxx-sanitizer-configuration-lib#compile-pic-types-cxx-sanitizer-configuration.c.oa34ca9a7,gcc-5-glibc-2.23/types-cxx-sanitizer-configuration.c.o): previous definition here
```
Buck generates ghci libraries with the corresponding binary rules that may be run in the intereactive mode. Each of these rules also get corresponding sanitizer configuration library. In parallel, buck also supports dlopened libraries that are actively used by sigma, which forces buck to include all of the dependencies of a dlopened library into the top level binary. That multiple sanitizer configuration libraries to be pulled into one binary rule. To fix the described problem add special filtering to filter out the genrated libraries using pattern ``__generated-lib__```

Reviewed By: andrewjcg

Differential Revision: D7324304

fbshipit-source-id: f40f365ccf9de51557fc837319b255add8da99d4